turns out the executable-war is magic.
without it JenkinsRule tests fail with things like

```
  26.565 [id=86]        WARNING
  h.ExtensionFinder$GuiceFinder$FaultTolerantScope$1#error: Failed to
  instantiate Key[type=jenkins.slaves.JnlpSlaveAgentProtocol4,
  annotation=[none]]; skipping this component
  java.security.KeyStoreException: JENKINS-41987: no X509Certificate
  found; perhaps instance-identity module is missing or too old
  at
  jenkins.slaves.JnlpSlaveAgentProtocol4.<init>(JnlpSlaveAgentProtocol4.java:105)
  at
  jenkins.slaves.JnlpSlaveAgentProtocol4$$FastClassByGuice$$b470638c.newInstance(<generated>)
  at
  com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
  at
  com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
  at
  com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
  at
  com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
  at
  com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
  at
  com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
  at
  hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:567)
  at
  com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
  at
  com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
  at
  com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
  at
  com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
  at
  com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
  at
  com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
  at
  com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
  Caused: com.google.inject.ProvisionException: Unable to provision, see
  the following errors:
  1) Error injecting constructor, java.security.KeyStoreException:
  JENKINS-41987: no X509Certificate found; perhaps instance-identity
  module is missing or too old
  at
  jenkins.slaves.JnlpSlaveAgentProtocol4.<init>(JnlpSlaveAgentProtocol4.java:101)
  1 error
  at
  com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:52)
  at
  com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
  at
  hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:439)
  at
  com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
  at
  com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
  at
  com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
  at
  com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
  at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:401)
  at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:392)
  at
  hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:344)
  at hudson.ExtensionList.load(ExtensionList.java:381)
  at hudson.ExtensionList.ensureLoaded(ExtensionList.java:317)
  at hudson.ExtensionList.iterator(ExtensionList.java:172)
  at jenkins.AgentProtocol.of(AgentProtocol.java:112)
  at
  hudson.TcpSlaveAgentListener$ConnectionHandler.run(TcpSlaveAgentListener.java:284)
```